### ISSUE TITLE
WARNING: MAX TRANSFER LOGS EXCEEDED

### ISSUE THREAD

**Issue by h0rizons** [waatk/ercholders#1]
Yo, thank you so much for this! 

When running I keep getting this error popping up and wasn't sure what to do.

`WARNING: MAX TRANSFER LOGS EXCEEDED
Scanning from 14181683 to 14181690, increment=7`

**Comment by waatk** [comment]
That just means that the api call to etherscan returned more than 1000 event logs, so the program will go back and subdivide the block interval for the next query.  It would only be a problem if it went to increment=1 and said the same thing.  That would mean there was more than 1000 logs in one block, and some information would be missing.
